### ISSUE TITLE
Chrome issue: Clicking on a hit and going back via back button invalidates next search

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#124]
When clicking on a link on the search page following it to GetBooks, then hitting the back button and doing a new search always no results are found. This is due to an error where search only ocr and search only title gets set to true at the same time even when no search options were selected before going to a book.

**Comment by georgbuechner** [comment]
Has this been tested on the developerbranch too? I installed chrome and did a few tests and this error did not occure.

**Comment by sladen** [comment]
Can be avoided by using the same parameter;  eg. `scope=x`.  ie. `scope=metadata` (`title`), `scope=body` (`ocr`), and default `scope=all`.

**Comment by georgbuechner** [comment]
Great Idea. Can someone confirm, that the issue is solved, as I couldn't reproduce it?

**Comment by ekoehring** [comment]
I still have the issue under chrome (both ubuntu and android), sorry... could only test the stable version, 9991 branch says server is restarting

**Comment by georgbuechner** [comment]
Could you test on the developer version? The change is not set on the main server jet.
https://clas-digital.uni-frankfurt.de:9991/

**Comment by ekoehring** [comment]
could only test the stable version, 9991 branch says server is restarting

**Comment by ekoehring** [comment]
ah, now: yes, solved!

**Comment by georgbuechner** [comment]
great!
